version: "3"

services:
  payment-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: payment-container
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m